<?php
return [
    'resource_category' => [
        1 => 'Policy, Procedures and Guidelines',
        2 => 'General Forms',
        3 => 'Staff Form',
        8 => 'Intake Forms',
        9 => 'Incident Report',
        5 => 'Home and Community Support Resources',
        6 => 'Residential Support Resources',
        7 => 'Support Coordination Resources',
        11 =>'High Intensity Support',
        10 => 'Other',
    ],
    'city_name' => [
        0 => 'Please Select',
        1 => 'Melbourne',
        2 => 'Perth',
        3 => 'Hobart',
    ],
    'state_names' => [
        1 => 'New South Wales',
        2 => 'Victoria',
        3 => 'Queensland',
        4 => 'Western Australia',
        5 => 'South Australia',
        6 => 'Tasmania',
        7 => 'Australian Capital Territory',
        8 => 'Northern Territory',
    ],
    'service_lists' => [
        1 => 'Assessment Counselling and Therapy',
        2 => 'Assistance for Daily Activities',
        3 => 'High intensity Support',
        4 => 'SIL/STA/MTA',
        5 => 'Participate community',
        6 => 'Group recreation and leisure',
        7 => 'Support coordination',
        8 => 'Individual skill development and Coaching',
        9 => 'Assistive Technology',
        10 => 'Meal delivery',
        11 => 'Community Nursing',
        12 => 'SDA',
        13 => 'Assist Employment',
        14 => 'Cleaning & Gardening',
        15 => 'Mental health services',
        16 => 'Other',
    ],
    'overall_satisfaction_willingness' => [
        1 => 'Excellent',
        2 => 'Good',
        3 => 'Average',
        4 => 'not at all',
    ],
    'employees_behave' => [
        1 => 'Very satisfied',
        2 => 'Somewhat satisfied',
        3 => 'not so satisfied',
        4 => 'Not satisfied at all',
    ],
    'resolving_concerns' => [
        1 => 'Very well',
        2 => 'Somewhat well',
        3 => 'Not so well',
        4 => 'Not at all well',
    ],
    'explain_info' => [
        1 => 'Very well',
        2 => 'Somewhat well',
        3 => 'Not so well',
        4 => 'Not at all',
    ],
    'rate_quality_service' => [
        1 => 'Excellent',
        2 => 'Good',
        3 => 'Average',
        4 => 'not satisfied',
    ],
    'recommend_friend_colleague' => [
        1 => 'Always',
        2 => 'May be',
        3 => 'Not sure',
        4 => 'Not at all',
    ],
    'meets_your_needs' => [
        1 => 'Very well',
        2 => 'Somewhat Well',
        3 => 'Not so well',
        4 => 'Not good at all',
    ],
    'enjoy_working' => [
        1 => 'A lot',
        2 => 'A little',
        3 => 'A moderate amount',
        4 => 'Not at all',
    ],
    'satisfied_career_growth' => [
        1 => 'Extremely Satisfied',
        2 => 'Very satisfied',
        3 => 'Somewhat satisfied',
        4 => 'Not so satisfied',
        5 => 'Not satisfied at all',
    ],
    'match_strengths' => [
        1 => 'Extremely well',
        2 => 'Very well',
        3 => 'Somewhat well',
        4 => 'Not so well',
        5 => 'Not at all well',
    ],
    'work_life_balance' => [
        1 => 'Extremely Satisfied',
        2 => 'Very satisfied',
        3 => 'Somewhat satisfied',
        4 => 'Not so satisfied',
        5 => 'Not at all satisfied',
    ],
    'comfortable_voicing' => [
        1 => 'Extremely comfortable',
        2 => 'Very comfortable',
        3 => 'Somewhat comfortable',
        4 => 'Not so Comfortable',
        5 => 'Not at all comfortable',
    ],
    'feel_stressed_work' => [
        1 => 'Always',
        2 => 'Most of the time',
        3 => 'About half of the time',
        4 => 'Once in a while',
        5 => 'Never',
    ],
    'meaningful_work' => [
        1 => 'Extremely meaningful',
        2 => 'Very meaningful',
        3 => 'Somewhat meaningful',
        4 => 'Not so meaningful',
        5 => 'Not at all meaningful',
    ],
];