{{--
|--------------------------------------------------------------------------
| Page: Medication Form
|--------------------------------------------------------------------------
| Medication administration record (MAR) entry form.
--}}
@extends('layouts.app', ['title' => 'Medication Incident / Error Form'])
@section('title','Medication Incident / Error Form')
@section('content')
<section class="bg-white dark:bg-ink-900 rounded-2xl shadow-soft border border-slate-100 dark:border-ink-800 p-6 mb-6">
  <h3 class="text-base font-semibold mb-1">Part 1 · Person Reporting Details</h3>
  <div class="h-px bg-slate-100 dark:bg-ink-800 mb-5"></div>
  <div class="grid md:grid-cols-12 gap-4"><div class="md:col-span-6"><label class="text-sm font-medium text-slate-700 dark:text-ink-200">Name of person reporting</label><div class="mt-1.5"><input type="text" placeholder="" class="w-full px-3.5 py-2.5 rounded-lg border border-slate-200 dark:border-ink-800 focus:border-brand-500 focus:ring-2 focus:ring-brand-100 outline-none text-sm" /></div></div><div class="md:col-span-6"><label class="text-sm font-medium text-slate-700 dark:text-ink-200">Position</label><div class="mt-1.5"><input type="text" placeholder="" class="w-full px-3.5 py-2.5 rounded-lg border border-slate-200 dark:border-ink-800 focus:border-brand-500 focus:ring-2 focus:ring-brand-100 outline-none text-sm" /></div></div><div class="md:col-span-4"><label class="text-sm font-medium text-slate-700 dark:text-ink-200">Date incident/error occurred</label><div class="mt-1.5"><input type="date" placeholder="" class="w-full px-3.5 py-2.5 rounded-lg border border-slate-200 dark:border-ink-800 focus:border-brand-500 focus:ring-2 focus:ring-brand-100 outline-none text-sm" /></div></div><div class="md:col-span-4"><label class="text-sm font-medium text-slate-700 dark:text-ink-200">Time of incident/error</label><div class="mt-1.5"><input type="time" placeholder="" class="w-full px-3.5 py-2.5 rounded-lg border border-slate-200 dark:border-ink-800 focus:border-brand-500 focus:ring-2 focus:ring-brand-100 outline-none text-sm" /></div></div><div class="md:col-span-4"><label class="text-sm font-medium text-slate-700 dark:text-ink-200">Date incident/error reported</label><div class="mt-1.5"><input type="date" placeholder="" class="w-full px-3.5 py-2.5 rounded-lg border border-slate-200 dark:border-ink-800 focus:border-brand-500 focus:ring-2 focus:ring-brand-100 outline-none text-sm" /></div></div><div class="md:col-span-12"><label class="text-sm font-medium text-slate-700 dark:text-ink-200">Incident/Error reported to</label><div class="mt-1.5"><input type="text" placeholder="" class="w-full px-3.5 py-2.5 rounded-lg border border-slate-200 dark:border-ink-800 focus:border-brand-500 focus:ring-2 focus:ring-brand-100 outline-none text-sm" /></div></div></div>
</section>
<section class="bg-white dark:bg-ink-900 rounded-2xl shadow-soft border border-slate-100 dark:border-ink-800 p-6 mb-6">
  <h3 class="text-base font-semibold mb-1">Part 2 · Client / Participant Details</h3>
  <div class="h-px bg-slate-100 dark:bg-ink-800 mb-5"></div>
  <div class="grid md:grid-cols-12 gap-4"><div class="md:col-span-6"><label class="text-sm font-medium text-slate-700 dark:text-ink-200">Client / Participant name</label><div class="mt-1.5"><input type="text" placeholder="" class="w-full px-3.5 py-2.5 rounded-lg border border-slate-200 dark:border-ink-800 focus:border-brand-500 focus:ring-2 focus:ring-brand-100 outline-none text-sm" /></div></div><div class="md:col-span-6"><label class="text-sm font-medium text-slate-700 dark:text-ink-200">Location of incident/error</label><div class="mt-1.5"><input type="text" placeholder="" class="w-full px-3.5 py-2.5 rounded-lg border border-slate-200 dark:border-ink-800 focus:border-brand-500 focus:ring-2 focus:ring-brand-100 outline-none text-sm" /></div></div><div class="md:col-span-12"><label class="text-sm font-medium text-slate-700 dark:text-ink-200">Name of person responsible (if not reporter)</label><div class="mt-1.5"><input type="text" placeholder="" class="w-full px-3.5 py-2.5 rounded-lg border border-slate-200 dark:border-ink-800 focus:border-brand-500 focus:ring-2 focus:ring-brand-100 outline-none text-sm" /></div></div></div>
</section>
<section class="bg-white dark:bg-ink-900 rounded-2xl shadow-soft border border-slate-100 dark:border-ink-800 p-6 mb-6">
  <h3 class="text-base font-semibold mb-1">Part 3 · Incident Details</h3>
  <div class="h-px bg-slate-100 dark:bg-ink-800 mb-5"></div>
  <div class="grid md:grid-cols-12 gap-4"><div class="md:col-span-12"><label class="text-sm font-medium text-slate-700 dark:text-ink-200">Type of incident / error</label><div class="mt-1.5"><div class="grid sm:grid-cols-2 gap-2"><label class="flex items-center gap-2.5 p-2.5 rounded-lg border border-slate-200 dark:border-ink-800 hover:border-brand-300 hover:bg-brand-50/30 cursor-pointer text-sm">
          <input type="checkbox" name="med_type[]" class="peer sr-only">
          <span class="chk-box w-4 h-4 rounded border border-slate-300 dark:border-ink-700 grid place-items-center"><svg class="w-3 h-3 text-white opacity-0" fill="none" stroke="currentColor" stroke-width="3" viewBox="0 0 24 24"><path d="M5 13l4 4L19 7"/></svg></span>
          <span>Wrong Client/Participant</span></label><label class="flex items-center gap-2.5 p-2.5 rounded-lg border border-slate-200 dark:border-ink-800 hover:border-brand-300 hover:bg-brand-50/30 cursor-pointer text-sm">
          <input type="checkbox" name="med_type[]" class="peer sr-only">
          <span class="chk-box w-4 h-4 rounded border border-slate-300 dark:border-ink-700 grid place-items-center"><svg class="w-3 h-3 text-white opacity-0" fill="none" stroke="currentColor" stroke-width="3" viewBox="0 0 24 24"><path d="M5 13l4 4L19 7"/></svg></span>
          <span>Wrong Date</span></label><label class="flex items-center gap-2.5 p-2.5 rounded-lg border border-slate-200 dark:border-ink-800 hover:border-brand-300 hover:bg-brand-50/30 cursor-pointer text-sm">
          <input type="checkbox" name="med_type[]" class="peer sr-only">
          <span class="chk-box w-4 h-4 rounded border border-slate-300 dark:border-ink-700 grid place-items-center"><svg class="w-3 h-3 text-white opacity-0" fill="none" stroke="currentColor" stroke-width="3" viewBox="0 0 24 24"><path d="M5 13l4 4L19 7"/></svg></span>
          <span>Wrong Time</span></label><label class="flex items-center gap-2.5 p-2.5 rounded-lg border border-slate-200 dark:border-ink-800 hover:border-brand-300 hover:bg-brand-50/30 cursor-pointer text-sm">
          <input type="checkbox" name="med_type[]" class="peer sr-only">
          <span class="chk-box w-4 h-4 rounded border border-slate-300 dark:border-ink-700 grid place-items-center"><svg class="w-3 h-3 text-white opacity-0" fill="none" stroke="currentColor" stroke-width="3" viewBox="0 0 24 24"><path d="M5 13l4 4L19 7"/></svg></span>
          <span>Wrong Type of Medication</span></label><label class="flex items-center gap-2.5 p-2.5 rounded-lg border border-slate-200 dark:border-ink-800 hover:border-brand-300 hover:bg-brand-50/30 cursor-pointer text-sm">
          <input type="checkbox" name="med_type[]" class="peer sr-only">
          <span class="chk-box w-4 h-4 rounded border border-slate-300 dark:border-ink-700 grid place-items-center"><svg class="w-3 h-3 text-white opacity-0" fill="none" stroke="currentColor" stroke-width="3" viewBox="0 0 24 24"><path d="M5 13l4 4L19 7"/></svg></span>
          <span>Wrong Route</span></label><label class="flex items-center gap-2.5 p-2.5 rounded-lg border border-slate-200 dark:border-ink-800 hover:border-brand-300 hover:bg-brand-50/30 cursor-pointer text-sm">
          <input type="checkbox" name="med_type[]" class="peer sr-only">
          <span class="chk-box w-4 h-4 rounded border border-slate-300 dark:border-ink-700 grid place-items-center"><svg class="w-3 h-3 text-white opacity-0" fill="none" stroke="currentColor" stroke-width="3" viewBox="0 0 24 24"><path d="M5 13l4 4L19 7"/></svg></span>
          <span>Wrong Dose</span></label><label class="flex items-center gap-2.5 p-2.5 rounded-lg border border-slate-200 dark:border-ink-800 hover:border-brand-300 hover:bg-brand-50/30 cursor-pointer text-sm">
          <input type="checkbox" name="med_type[]" class="peer sr-only">
          <span class="chk-box w-4 h-4 rounded border border-slate-300 dark:border-ink-700 grid place-items-center"><svg class="w-3 h-3 text-white opacity-0" fill="none" stroke="currentColor" stroke-width="3" viewBox="0 0 24 24"><path d="M5 13l4 4L19 7"/></svg></span>
          <span>Incorrect Documentation</span></label><label class="flex items-center gap-2.5 p-2.5 rounded-lg border border-slate-200 dark:border-ink-800 hover:border-brand-300 hover:bg-brand-50/30 cursor-pointer text-sm">
          <input type="checkbox" name="med_type[]" class="peer sr-only">
          <span class="chk-box w-4 h-4 rounded border border-slate-300 dark:border-ink-700 grid place-items-center"><svg class="w-3 h-3 text-white opacity-0" fill="none" stroke="currentColor" stroke-width="3" viewBox="0 0 24 24"><path d="M5 13l4 4L19 7"/></svg></span>
          <span>Pharmacy Error</span></label><label class="flex items-center gap-2.5 p-2.5 rounded-lg border border-slate-200 dark:border-ink-800 hover:border-brand-300 hover:bg-brand-50/30 cursor-pointer text-sm">
          <input type="checkbox" name="med_type[]" class="peer sr-only">
          <span class="chk-box w-4 h-4 rounded border border-slate-300 dark:border-ink-700 grid place-items-center"><svg class="w-3 h-3 text-white opacity-0" fill="none" stroke="currentColor" stroke-width="3" viewBox="0 0 24 24"><path d="M5 13l4 4L19 7"/></svg></span>
          <span>Client refusal</span></label><label class="flex items-center gap-2.5 p-2.5 rounded-lg border border-slate-200 dark:border-ink-800 hover:border-brand-300 hover:bg-brand-50/30 cursor-pointer text-sm">
          <input type="checkbox" name="med_type[]" class="peer sr-only">
          <span class="chk-box w-4 h-4 rounded border border-slate-300 dark:border-ink-700 grid place-items-center"><svg class="w-3 h-3 text-white opacity-0" fill="none" stroke="currentColor" stroke-width="3" viewBox="0 0 24 24"><path d="M5 13l4 4L19 7"/></svg></span>
          <span>Other (please specify)</span></label></div></div></div><div class="md:col-span-12"><label class="text-sm font-medium text-slate-700 dark:text-ink-200">Incident background (what was client doing?)</label><div class="mt-1.5"><textarea rows="4" placeholder="" class="w-full px-3.5 py-2.5 rounded-lg border border-slate-200 dark:border-ink-800 focus:border-brand-500 focus:ring-2 focus:ring-brand-100 outline-none text-sm"></textarea></div></div><div class="md:col-span-12"><label class="text-sm font-medium text-slate-700 dark:text-ink-200">Details of incident/error (observations during & following)</label><div class="mt-1.5"><textarea rows="4" placeholder="" class="w-full px-3.5 py-2.5 rounded-lg border border-slate-200 dark:border-ink-800 focus:border-brand-500 focus:ring-2 focus:ring-brand-100 outline-none text-sm"></textarea></div></div><div class="md:col-span-12"><label class="text-sm font-medium text-slate-700 dark:text-ink-200">Cause(s) or contributing factor(s)</label><div class="mt-1.5"><div class="grid sm:grid-cols-2 gap-2"><label class="flex items-center gap-2.5 p-2.5 rounded-lg border border-slate-200 dark:border-ink-800 hover:border-brand-300 hover:bg-brand-50/30 cursor-pointer text-sm">
          <input type="checkbox" name="med_cause[]" class="peer sr-only">
          <span class="chk-box w-4 h-4 rounded border border-slate-300 dark:border-ink-700 grid place-items-center"><svg class="w-3 h-3 text-white opacity-0" fill="none" stroke="currentColor" stroke-width="3" viewBox="0 0 24 24"><path d="M5 13l4 4L19 7"/></svg></span>
          <span>Missing Information</span></label><label class="flex items-center gap-2.5 p-2.5 rounded-lg border border-slate-200 dark:border-ink-800 hover:border-brand-300 hover:bg-brand-50/30 cursor-pointer text-sm">
          <input type="checkbox" name="med_cause[]" class="peer sr-only">
          <span class="chk-box w-4 h-4 rounded border border-slate-300 dark:border-ink-700 grid place-items-center"><svg class="w-3 h-3 text-white opacity-0" fill="none" stroke="currentColor" stroke-width="3" viewBox="0 0 24 24"><path d="M5 13l4 4L19 7"/></svg></span>
          <span>Missing Labels</span></label><label class="flex items-center gap-2.5 p-2.5 rounded-lg border border-slate-200 dark:border-ink-800 hover:border-brand-300 hover:bg-brand-50/30 cursor-pointer text-sm">
          <input type="checkbox" name="med_cause[]" class="peer sr-only">
          <span class="chk-box w-4 h-4 rounded border border-slate-300 dark:border-ink-700 grid place-items-center"><svg class="w-3 h-3 text-white opacity-0" fill="none" stroke="currentColor" stroke-width="3" viewBox="0 0 24 24"><path d="M5 13l4 4L19 7"/></svg></span>
          <span>Storage</span></label><label class="flex items-center gap-2.5 p-2.5 rounded-lg border border-slate-200 dark:border-ink-800 hover:border-brand-300 hover:bg-brand-50/30 cursor-pointer text-sm">
          <input type="checkbox" name="med_cause[]" class="peer sr-only">
          <span class="chk-box w-4 h-4 rounded border border-slate-300 dark:border-ink-700 grid place-items-center"><svg class="w-3 h-3 text-white opacity-0" fill="none" stroke="currentColor" stroke-width="3" viewBox="0 0 24 24"><path d="M5 13l4 4L19 7"/></svg></span>
          <span>Delivery Device issues</span></label><label class="flex items-center gap-2.5 p-2.5 rounded-lg border border-slate-200 dark:border-ink-800 hover:border-brand-300 hover:bg-brand-50/30 cursor-pointer text-sm">
          <input type="checkbox" name="med_cause[]" class="peer sr-only">
          <span class="chk-box w-4 h-4 rounded border border-slate-300 dark:border-ink-700 grid place-items-center"><svg class="w-3 h-3 text-white opacity-0" fill="none" stroke="currentColor" stroke-width="3" viewBox="0 0 24 24"><path d="M5 13l4 4L19 7"/></svg></span>
          <span>Environmental</span></label><label class="flex items-center gap-2.5 p-2.5 rounded-lg border border-slate-200 dark:border-ink-800 hover:border-brand-300 hover:bg-brand-50/30 cursor-pointer text-sm">
          <input type="checkbox" name="med_cause[]" class="peer sr-only">
          <span class="chk-box w-4 h-4 rounded border border-slate-300 dark:border-ink-700 grid place-items-center"><svg class="w-3 h-3 text-white opacity-0" fill="none" stroke="currentColor" stroke-width="3" viewBox="0 0 24 24"><path d="M5 13l4 4L19 7"/></svg></span>
          <span>Training Deficit</span></label><label class="flex items-center gap-2.5 p-2.5 rounded-lg border border-slate-200 dark:border-ink-800 hover:border-brand-300 hover:bg-brand-50/30 cursor-pointer text-sm">
          <input type="checkbox" name="med_cause[]" class="peer sr-only">
          <span class="chk-box w-4 h-4 rounded border border-slate-300 dark:border-ink-700 grid place-items-center"><svg class="w-3 h-3 text-white opacity-0" fill="none" stroke="currentColor" stroke-width="3" viewBox="0 0 24 24"><path d="M5 13l4 4L19 7"/></svg></span>
          <span>Other</span></label></div></div></div><div class="md:col-span-12"><label class="text-sm font-medium text-slate-700 dark:text-ink-200">Immediate action taken</label><div class="mt-1.5"><div class="grid sm:grid-cols-2 gap-2"><label class="flex items-center gap-2.5 p-2.5 rounded-lg border border-slate-200 dark:border-ink-800 hover:border-brand-300 hover:bg-brand-50/30 cursor-pointer text-sm">
          <input type="checkbox" name="med_action[]" class="peer sr-only">
          <span class="chk-box w-4 h-4 rounded border border-slate-300 dark:border-ink-700 grid place-items-center"><svg class="w-3 h-3 text-white opacity-0" fill="none" stroke="currentColor" stroke-width="3" viewBox="0 0 24 24"><path d="M5 13l4 4L19 7"/></svg></span>
          <span>Notified to on call</span></label><label class="flex items-center gap-2.5 p-2.5 rounded-lg border border-slate-200 dark:border-ink-800 hover:border-brand-300 hover:bg-brand-50/30 cursor-pointer text-sm">
          <input type="checkbox" name="med_action[]" class="peer sr-only">
          <span class="chk-box w-4 h-4 rounded border border-slate-300 dark:border-ink-700 grid place-items-center"><svg class="w-3 h-3 text-white opacity-0" fill="none" stroke="currentColor" stroke-width="3" viewBox="0 0 24 24"><path d="M5 13l4 4L19 7"/></svg></span>
          <span>Called nurse On call</span></label><label class="flex items-center gap-2.5 p-2.5 rounded-lg border border-slate-200 dark:border-ink-800 hover:border-brand-300 hover:bg-brand-50/30 cursor-pointer text-sm">
          <input type="checkbox" name="med_action[]" class="peer sr-only">
          <span class="chk-box w-4 h-4 rounded border border-slate-300 dark:border-ink-700 grid place-items-center"><svg class="w-3 h-3 text-white opacity-0" fill="none" stroke="currentColor" stroke-width="3" viewBox="0 0 24 24"><path d="M5 13l4 4L19 7"/></svg></span>
          <span>Notified to Line Manager</span></label><label class="flex items-center gap-2.5 p-2.5 rounded-lg border border-slate-200 dark:border-ink-800 hover:border-brand-300 hover:bg-brand-50/30 cursor-pointer text-sm">
          <input type="checkbox" name="med_action[]" class="peer sr-only">
          <span class="chk-box w-4 h-4 rounded border border-slate-300 dark:border-ink-700 grid place-items-center"><svg class="w-3 h-3 text-white opacity-0" fill="none" stroke="currentColor" stroke-width="3" viewBox="0 0 24 24"><path d="M5 13l4 4L19 7"/></svg></span>
          <span>Notified Client/Participant (and/or Authorised Rep)</span></label><label class="flex items-center gap-2.5 p-2.5 rounded-lg border border-slate-200 dark:border-ink-800 hover:border-brand-300 hover:bg-brand-50/30 cursor-pointer text-sm">
          <input type="checkbox" name="med_action[]" class="peer sr-only">
          <span class="chk-box w-4 h-4 rounded border border-slate-300 dark:border-ink-700 grid place-items-center"><svg class="w-3 h-3 text-white opacity-0" fill="none" stroke="currentColor" stroke-width="3" viewBox="0 0 24 24"><path d="M5 13l4 4L19 7"/></svg></span>
          <span>Notified Pharmacy</span></label><label class="flex items-center gap-2.5 p-2.5 rounded-lg border border-slate-200 dark:border-ink-800 hover:border-brand-300 hover:bg-brand-50/30 cursor-pointer text-sm">
          <input type="checkbox" name="med_action[]" class="peer sr-only">
          <span class="chk-box w-4 h-4 rounded border border-slate-300 dark:border-ink-700 grid place-items-center"><svg class="w-3 h-3 text-white opacity-0" fill="none" stroke="currentColor" stroke-width="3" viewBox="0 0 24 24"><path d="M5 13l4 4L19 7"/></svg></span>
          <span>Notified General Practitioner</span></label><label class="flex items-center gap-2.5 p-2.5 rounded-lg border border-slate-200 dark:border-ink-800 hover:border-brand-300 hover:bg-brand-50/30 cursor-pointer text-sm">
          <input type="checkbox" name="med_action[]" class="peer sr-only">
          <span class="chk-box w-4 h-4 rounded border border-slate-300 dark:border-ink-700 grid place-items-center"><svg class="w-3 h-3 text-white opacity-0" fill="none" stroke="currentColor" stroke-width="3" viewBox="0 0 24 24"><path d="M5 13l4 4L19 7"/></svg></span>
          <span>Telephoned Ambulance</span></label><label class="flex items-center gap-2.5 p-2.5 rounded-lg border border-slate-200 dark:border-ink-800 hover:border-brand-300 hover:bg-brand-50/30 cursor-pointer text-sm">
          <input type="checkbox" name="med_action[]" class="peer sr-only">
          <span class="chk-box w-4 h-4 rounded border border-slate-300 dark:border-ink-700 grid place-items-center"><svg class="w-3 h-3 text-white opacity-0" fill="none" stroke="currentColor" stroke-width="3" viewBox="0 0 24 24"><path d="M5 13l4 4L19 7"/></svg></span>
          <span>Other</span></label></div></div></div></div>
</section>
<section class="bg-white dark:bg-ink-900 rounded-2xl shadow-soft border border-slate-100 dark:border-ink-800 p-6 mb-6">
  <h3 class="text-base font-semibold mb-1">Part 4 · Manager Report</h3>
  <div class="h-px bg-slate-100 dark:bg-ink-800 mb-5"></div>
  <div class="grid md:grid-cols-12 gap-4"><div class="md:col-span-12"><label class="text-sm font-medium text-slate-700 dark:text-ink-200">Follow-up action(s)</label><div class="mt-1.5"><div class="grid sm:grid-cols-2 gap-2"><label class="flex items-center gap-2.5 p-2.5 rounded-lg border border-slate-200 dark:border-ink-800 hover:border-brand-300 hover:bg-brand-50/30 cursor-pointer text-sm">
          <input type="checkbox" name="med_follow[]" class="peer sr-only">
          <span class="chk-box w-4 h-4 rounded border border-slate-300 dark:border-ink-700 grid place-items-center"><svg class="w-3 h-3 text-white opacity-0" fill="none" stroke="currentColor" stroke-width="3" viewBox="0 0 24 24"><path d="M5 13l4 4L19 7"/></svg></span>
          <span>Resolved with Pharmacy</span></label><label class="flex items-center gap-2.5 p-2.5 rounded-lg border border-slate-200 dark:border-ink-800 hover:border-brand-300 hover:bg-brand-50/30 cursor-pointer text-sm">
          <input type="checkbox" name="med_follow[]" class="peer sr-only">
          <span class="chk-box w-4 h-4 rounded border border-slate-300 dark:border-ink-700 grid place-items-center"><svg class="w-3 h-3 text-white opacity-0" fill="none" stroke="currentColor" stroke-width="3" viewBox="0 0 24 24"><path d="M5 13l4 4L19 7"/></svg></span>
          <span>Resolved with General Practitioner</span></label><label class="flex items-center gap-2.5 p-2.5 rounded-lg border border-slate-200 dark:border-ink-800 hover:border-brand-300 hover:bg-brand-50/30 cursor-pointer text-sm">
          <input type="checkbox" name="med_follow[]" class="peer sr-only">
          <span class="chk-box w-4 h-4 rounded border border-slate-300 dark:border-ink-700 grid place-items-center"><svg class="w-3 h-3 text-white opacity-0" fill="none" stroke="currentColor" stroke-width="3" viewBox="0 0 24 24"><path d="M5 13l4 4L19 7"/></svg></span>
          <span>Further training provided</span></label><label class="flex items-center gap-2.5 p-2.5 rounded-lg border border-slate-200 dark:border-ink-800 hover:border-brand-300 hover:bg-brand-50/30 cursor-pointer text-sm">
          <input type="checkbox" name="med_follow[]" class="peer sr-only">
          <span class="chk-box w-4 h-4 rounded border border-slate-300 dark:border-ink-700 grid place-items-center"><svg class="w-3 h-3 text-white opacity-0" fill="none" stroke="currentColor" stroke-width="3" viewBox="0 0 24 24"><path d="M5 13l4 4L19 7"/></svg></span>
          <span>Environmental factors resolved</span></label><label class="flex items-center gap-2.5 p-2.5 rounded-lg border border-slate-200 dark:border-ink-800 hover:border-brand-300 hover:bg-brand-50/30 cursor-pointer text-sm">
          <input type="checkbox" name="med_follow[]" class="peer sr-only">
          <span class="chk-box w-4 h-4 rounded border border-slate-300 dark:border-ink-700 grid place-items-center"><svg class="w-3 h-3 text-white opacity-0" fill="none" stroke="currentColor" stroke-width="3" viewBox="0 0 24 24"><path d="M5 13l4 4L19 7"/></svg></span>
          <span>Other</span></label></div></div></div><div class="md:col-span-12"><label class="text-sm font-medium text-slate-700 dark:text-ink-200">Follow-up action(s) — detailed explanation</label><div class="mt-1.5"><textarea rows="5" placeholder="" class="w-full px-3.5 py-2.5 rounded-lg border border-slate-200 dark:border-ink-800 focus:border-brand-500 focus:ring-2 focus:ring-brand-100 outline-none text-sm"></textarea></div></div><div class="md:col-span-4"><label class="text-sm font-medium text-slate-700 dark:text-ink-200">Action taken by</label><div class="mt-1.5"><input type="text" placeholder="" class="w-full px-3.5 py-2.5 rounded-lg border border-slate-200 dark:border-ink-800 focus:border-brand-500 focus:ring-2 focus:ring-brand-100 outline-none text-sm" /></div></div><div class="md:col-span-4"><label class="text-sm font-medium text-slate-700 dark:text-ink-200">Date completed</label><div class="mt-1.5"><input type="date" placeholder="" class="w-full px-3.5 py-2.5 rounded-lg border border-slate-200 dark:border-ink-800 focus:border-brand-500 focus:ring-2 focus:ring-brand-100 outline-none text-sm" /></div></div><div class="md:col-span-4"><label class="text-sm font-medium text-slate-700 dark:text-ink-200">Signature</label><div class="mt-1.5"><input type="text" placeholder="" class="w-full px-3.5 py-2.5 rounded-lg border border-slate-200 dark:border-ink-800 focus:border-brand-500 focus:ring-2 focus:ring-brand-100 outline-none text-sm" /></div></div></div>
</section>
<div class="flex justify-end gap-2 mb-10">
  <button class="px-4 py-2.5 rounded-lg border border-slate-200 dark:border-ink-800 bg-white dark:bg-ink-900 text-sm font-medium">Cancel</button>
  <button class="px-5 py-2.5 rounded-lg bg-brand-600 hover:bg-brand-700 text-white text-sm font-semibold shadow-soft">Submit medication report</button>
</div>
@endsection
